### PR TITLE
Add an argument for disabling runtime binding

### PR DESCRIPTION
**Pull request by Fedorof**
This addresses the issue #23

### CODE REVIEW

**Comment by ivankorobkov** [comment]
Hi!

> If a user forgets to bind a class to an instance, in the best case she gets an exception like TypeError for abstract classes, typing variables, callables that require at least one argument and so on. Such messages are usually not helpful and sometimes obscuring.

One can see DI from two different point of views:
1) DI allows to *automatically instantiate* a graph of interdependent service instances, which _are_ a program.
2) DI allows to *dynamically structure* a program via late-binding of its dependencies.

I'm in favor of the first. Imagine a Twitter-like application:
```python

class Config:
    def __init__(self, dbconn=''):
        self.dbconn = dbconn


class Db:
    @inject.autoparams()
    def __init__(self, config: Config):
        pass


class Users:
    @inject.autoparams()
    def __init__(self, db: Db):
        pass


class Tweets:
    @inject.autoparams()
    def __init__(self, db: Db, users: Users):
        pass


class WsgiServer:
    @inject.autoparams()
    def __init__(self, tweets: Tweets, users: Users):
        pass	

```

In this case all dependencies are already specified. We only need to instantiate a graph of services with a custom `Config`:
```python

def main():
    config = Config.read_yaml("config.yaml")
    inject.configure(lambda binder: binder.bind(Config, config))
	
    # That's all!
```

However, if you really need to prevent `injector` from automatically instantiating objects, I am not against it, but it will not be the default behaviour.

Also, please, update readme in the pull request.

**Comment by Fedorof** [comment]
Good. Thank you. Updated the README, hope the text is Ok

**Comment by Fedorof** [comment]
Thank you for accepting the PR. Cold you please notify me when the new version is released? I would like to use the change in my current projects

**Comment by ivankorobkov** [comment]
Done. Added you to the contributers. https://pypi.org/project/Inject/

**Pull request merged**
