### PR TITLE
Merging type-hints into implementation (compatible with Python 2.7/3.5+)

### PR DESCRIPTION
**Pull request by andrewborba10**
The intention here is two-fold (broken down into two commits):
- Modify type-hints to support Hashable bindings and other improvements
- Merge these type-hints into the .py file instead of having a .pyi file.

I was able to run unit tests for both this project and my own. For python-inject I ran the tests against Python 2.7 and 3.6. For my own project, I ran the unit tests for Python 3.7 and 3.6 (my project doesn't support Python 2.7).

### CODE REVIEW

**Comment by andrewborba10** [comment]
As you can see, the CI is failing because of the typing module not being available. I'm struggling to figure out how to make it a dependency of this project. All I know is that 'pip install typing' needs to be run at some point, I'm just not sure how to specify that as a dependency in setup.py, or if that's even the right place for this.

**Comment by andrewborba10** [comment]
Ok, I figured it out. I had to migrate to the 'setuptools' module instead of 'distutils' for the setup.py. Everything is exactly identical except setuptools supports the 'install_requires' field which will pip install modules listed there when installing with setup.py. One other change I had to make it setting the version to "3.5.1.dev0" because the setuptools module enforces some PEP that has stricter requirements on version strings.

**Comment by andrewborba10** [comment]
Looks like Python 3.3 is unsupported by the typing module. Would you consider dropping support for it as well, given that this version of Python hit EOL in 2017?

**Comment by ivankorobkov** [comment]
Sure, you can drop Python 3.3 support. I will merge it later today.

**Comment by ivankorobkov** [comment]
Sorry for the delay. I have released 3.5.2 https://pypi.org/project/Inject/
Also I have added you to the contributed section in readme.

**Pull request merged**
