### PR TITLE
Make autoparams work with keyword-only parameters:

### PR DESCRIPTION
**Pull request by cselvaraj**
- v3.5.0 lost some compatibility with keyword-only parameters
- PEP8 fixes
- sync up versions and increment to a dev version

### CODE REVIEW

**Comment by ivankorobkov** [comment]
Hi. Sorry for the delay. I'll look into it tomorrow.

**Comment by ivankorobkov** [comment]
Looks good to me. Also, thanks for the code cleanup. I think, this should be released as 3.5.1, will do it this week.

**Comment by cselvaraj** [comment]
Sounds good.  Thanks, @ivankorobkov !

**Comment by ivankorobkov** [comment]
Released 3.5.1 https://pypi.org/project/Inject/

**Comment by ivankorobkov** [comment]
Sorry for the delay. I was a little busy these two weeks.

**Comment by cselvaraj** [comment]
No problem. Thanks!

**Pull request merged**
