### PR TITLE
Implement autoparams leveraging types annotations

### PR DESCRIPTION
**Pull request by Enforcer**
`autoparams` docs:
```python
"""
Return a decorator which automatically injects arguments into a function that uses type annotations.
    This is supported only in Python >= 3.5.

    For example::

        @inject.autoparams()
        def refresh_cache(cache: RedisCache, db: DbInterface):
            pass

    There is an option to specify which arguments we want to inject without attempts of injecting everything:

    For example::

        @inject.autoparams('cache', 'db')
        def sign_up(name, email, cache, db):
            pass
"""
```

### CODE REVIEW

**Comment by Enforcer** [comment]
@ivankorobkov  if this looks fine to you and you decide to merge, please release new version afterwards. For now I have no more ideas

**Comment by ivankorobkov** [comment]
Wow, that's a great one. Thanks for splitting the tests.

**Comment by ivankorobkov** [comment]
I will try to release a new version today if I have enough time.

**Comment by ivankorobkov** [comment]
I have added you autoparams example to the readme, added you to the contributors section and released version 3.4.0. As usual you can get it from PyPi https://pypi.org/project/Inject/

**Pull request merged**
